#!/usr/bin/env bash

docker exec -it $(source .env && docker ps | grep "http" | cut -d " " -f1) composer config --global discard-changes true
docker exec -it $(source .env && docker ps | grep "http" | cut -d " " -f1) COMPOSER_DISCARD_CHANGES=true composer $@ --no-interaction

# Checking if composer issue is resolved like this
# docker exec -it $(source .env && docker ps | grep "http" | cut -d " " -f1) /bin/chmod 777 "/app" -R

if [ "$1" = "package:install" ]; then
  echo "Restarting webserver"
  docker-compose restart http
fi

