#!/usr/bin/env bash
docker exec -it $(source .env && docker ps | grep "http" | cut -d " " -f1) composer $@
chmod 777 ./* -R

if [ "$1" = "package:install" ]; then
  echo "Restarting webserver"
  docker-compose restart http
fi

