version: '3'
# The creation of this file was inspired on
# http://www.inanzzz.com/index.php/post/su76/creating-apache-mysql-and-php-fpm-containers-for-a-web-application-with-docker-compose
services:
  http:
    build:
      context: docker/http
      args:
        - APACHE_ROOT_DIR=/app
    container_name: ${PROJECT_NAME}_http
    command: "/bin/bash -c \"chmod +x /scripts/init.sh; /scripts/init.sh\""
    volumes:
      - .:/app
      - ./docker/http/scripts:/scripts:rw
      - ./docker/http/includes:/includes
    ports:
      - ${WEB_PORT}:80
      - ${SSL_WEB_PORT}:443
    depends_on:
      - database
    networks:
      public_net:
        ipv4_address: ${WEB_IP}
    environment:
      - SYSTEM_ROOT=${SYSTEM_ROOT}
      - DEV_TOP_LEVEL_DOMAIN=${DEV_TOP_LEVEL_DOMAIN}
  database:
    build:
      context: docker/database
      args:
        - MYSQL_CONTAINER_USER=mysql
        - MYSQL_CONTAINER_GROUP=mysql
    container_name: ${PROJECT_NAME}_database
    command: "--default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp"
    volumes:
      - ../data/log/mysql:/var/log/mysql:rw
      - ../data/db:/var/lib/mysql:rw
    ports:
      - 3306:3306
    networks:
      public_net:
        ipv4_address: ${DATABASE_IP}
    environment:
      - MYSQL_CONTAINER_USER=mysql
      - MYSQL_CONTAINER_GROUP=mysql
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_IP=${DATABASE_IP}
networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
